spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/lacasolana
    username: lacasolana
    password: preguntar
    platform: postgresql
server:
   contextPath: /datos-generales-lacasolana
