spring:
  datasource: 
    url: jdbc:postgresql://192.168.67.76:5432/lacasolana
    username: lacasolana
    password: pretguntar
    platform: postgresql
server:
   contextPath: /operaciones-lacasolana
