spring:
  datasource: 
    url: jdbc:postgresql://192.168.67.76:5432/lacasolana
    username: lacasolana
    password: preguntar
    platform: postgresql
server:
   contextPath: /proveedores-lacasolana
